name: project-check

on: push

jobs:
  check:
    name: Check project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install deps
        run: make install

      - name: Run linter
        run: make lint

      - name: Run tests
        run: make test

      - name: Publish test-coverage to code climate
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          debug: true
