name: test

on: push

jobs:
  lint:
    name: Test project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install deps
        run: make install

      - name: Run test
        run: make test
